version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: quantedge
      POSTGRES_USER: quantedge_user
      POSTGRES_PASSWORD: quantedge_pass
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - quantedge_postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantedge_user -d quantedge"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  quantedge_postgres_data: